---
title             : "Curating Research Assets in Behavioral Sciences: A tutorial on managing research materials with R Studio & the Git version control system"
shorttitle        : "Curating Research Assets in Behavioral Sciences"

author: 
  - name: Matti Vuorre
    affiliation: 1
    corresponding: yes
    address: 406 Schermerhorn Hall, 1190 Amsterdam Avenue MC 5501, New York, NY 10027
    email: mv2521@columbia.edu
  - name          : ""
    affiliation   : ""
affiliation:
  - id            : "1"
    institution   : "Department of Psychology, Columbia University"
author_note: >
  Complete departmental affiliations for each author (note the indentation, if you start a new paragraph).

  Enter author note here.

abstract: >
  Enter abstract here (note the indentation, if you start a new paragraph).
  
keywords          : "keywords"
wordcount         : "X"
bibliography      : ["references.bib"]
figsintext        : yes
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : yes
lang              : "english"
class             : "man"
output            : papaja::apa6_pdf
---

```{r include = FALSE}
library(knitr)  # Make sure that knit directory is project root
library(papaja)
library(tidyverse)
```

# Introduction

The lack of reproducibility is an increasingly recognized problem across scientific disciplines, and calls for changing the scientific workflow to enhance it have been published in a wide range of research areas, including Biology [@markowetz_five_2015], Ecology [@ihle_striving_2017], Neuroscience [@eglen_toward_2017] and Psychology [@munafo_manifesto_2017]. However, although exhortations to focus on reproducibility in the scientific practice are now commonplace on the pages of leading scientific journals [@baker_1500_2016], only a small minority of researchers are familiar with the tools and practices that enable implementing reproducibility in the scientific workflow. Therefore, although there now is a broad consensus that efforts to improve reproducibility are important, and even on some of the tools that may allow to do so, materials instructing researchers in using them are lacking. In this tutorial paper, we present a detailed walk-through of the git version control system for behavioral scientists.

## Reproducibility

Consider the following [@ihle_striving_2017, p.2]: Have you ever found a mistake in your results without knowing what caused it? Forgot what analyses you have already done and how (and possibly, why)? Lost datasets or information about the cases or variables in a dataset? Struggled in redoing analyses when new data became available? Had difficulty understanding what data to use or how in a project that you inherited from another researcher? Answering any of these questions in the affirmative suggests that your work might benefit from improving reproducibility [@ihle_striving_2017].

But what exactly is reproducibility and why does it matter? Reproducibility can be defined as follows: "A research project is computationally reproducible if a second investigator (including you in the future) can recreate the final reported results of the project, including key quantitative findings, tables, and figures, given only a set of files and written instructions." [@kitzes_practice_2017] In the context of experimental Psychology, for example, a project would mean an experiment or a set of experiments investigating a theory or hypothesis, reported results would be a conference presentation or a submitted manuscript. In this field, key quantitative findings are usually probability values from statistical models, such as *p*-values, or tables of descriptive statistics such as (differences in) means.

Given this broad definition, here is an example of a non-reproducible project: A published journal article advertises a specific relationship between two variables, to some specified degree of uncertainty, but doesn't provide the raw data or code used to analyse it. An example of a reproducible project, on the other hand, provides a well organized package of i) the raw data supporting the claims made in the article, ii) the computer code (or steps of analysis) required to compute the summary and test statistics from the data, and iii) instructions on how to apply ii) to i), if it is not self-evident. Clearly, many projects fall in between, and can be partly reproducible--e.g. provide raw data but no code.

This definition makes clear an important distinction: reproducibility is not the same as replicability. Traditional methods and results sections in journal articles have focused on ensuring replicability (but not reproducibility) by giving detailed instructions on how to repeat the experiment and collect a data set *like* the original one. Viewed in this light, replicability is a broad methodological issue concerning the epistemology of the scientific claims; whereas reproducibility--the topic of this tutorial--concerns the minimal steps required to allow checking for the validity of the computations required to assert the scientific claim in the first place.

Although they are often conlated [TODO] reproducibility and replicability are, in fact, independent of one another. One might think that reproducibility [TODO Peng 2011?] is a requirement of replicability, but an experiment can be replicated even if the materials of the original study are not available for replicability. Likewise, the materials of a study might allow its results to be reproduced, yet the underlying scientific idea might not be replicable. Therefore, it is important to keep these two concepts distinct; in this manuscript we are interested in reproducibility. 

## Challenges to reproducibility

<!-- TODO work on motivating the use of Git: why is keeping track of materials an issue? Is it an issue? How does VCS help? -->

Although reproducibility might at first appear easy, it has in large parts failed in practice. For example, one survey of leading Psychology journals found that 34-58% of articles published between 1985 and 2013 had at least one inconsistently reported *p*-value [@nuijten_prevalence_2015]. Upon recalculation, the authors couldn't obtain the same *p*-values from the reported test statistics, and therefore these 34-58% of articles were, to some degree, non-reproducible.

Why, then, do so many research products fall short of the basic scientific standard of reproducibility? We suggest one reason is the poor level of organization and curation of all the research assets (data and code, usually) that play a part in creating the research product. Researchers usually have no formal methods or accepted gold standards for curating their research assets, and collaborative workflows, especially, are difficult to manage in a reproducible manner. When the complexity and amount of materials related to a project increases, it might be difficult to link analysis files to the correct data files, and track the evolution of both code and data throughout the research cycle.

In fact, the effort to organize and curate materials has been cited as an important reason for why data is so rarely shared in Psychology. In one study, researchers asked authors of 141 Psychology articles (with a total of 249 studies) to share their data for reanalysis [@wicherts_poor_2006]. 73% of the authors refused to share their data, and Wicherts et al. suggested that they did so because it takes considerable effort to clean, document and organize datasets. How could we make organizing and curating materials and data easier, so as to improve the reproducibility of our science?

## Aims of the article

Fortunately for the empirical sciences, challenges related to organizing and curating materials across time, space, and personnel have been solved to a high standard in computer science with Version Control Systems (VCS). In the remainder of this article, we introduce a popular VCS called Git, and illustrate its use in the scientific workflow with a hypothetical example project. In the tutorial below, we provide show how to use the Git VCS to curate your research materials by using text commands from the computers command line, and with a Graphical User Interface called R Studio.

# The Git version control system

VCSs are computer programs designed for "tracking changes in computer files and coordinating work on those files among multiple people" (Wikipedia). In this tutorial, we focus on the most widely used (within science) VCS, called Git. 

<!-- Insert illustration of VCS about here. -->

It is important to understand that unlike an operating system's (OS) default file viewer, such as Finder (Apple computers) or File Explorer (?? Windows), Git is not a standalone program for navigating files and folders on a computer. Instead, it adds functionality to the OSs existing file system, by making available a specific set of functions--either executed from the command line, or through a graphical user interface (GUI) / integrated development environment (IDE)--that allow taking snapshots of the project and its files, and distributing the work across multiple computers and users. To begin using Git, users must first download and install the Git software on their computers. Git is free and open source, works on Windows, Macintosh, and Linux OSs (among others), and is used by major software developers such as Microsoft, Google, and Facebook. It can be freely downloaded at <https://git-scm.com/>. 

## Installing Git

Even if you already have Git installed (some computers do) it is a good idea to install the latest version[^git-version], which can be downloaded as a standalone program from <https://git-scm.com/download>. Here, we provide more detailed instructions on installing Git for OS X and Windows, but Linux (and other OS) users can find instructions at the Git website (<https://git-scm.com/book/en/v2/Getting-Started-Installing-Git>). Along with install instructions, we detail how to configure the Git program so that it is ready to be used.

### OS X

Many OS X computers already have Git installed, especially those operating OS X 10.9 or higher, but it is good practice to install the latest version. The easiest way to update Git to the latest version is to download the installer from <http://git-scm.com/download/mac>, and install it like any other program. Once Git is installed, it can be used from the command line (the OS X command line is available through the Terminal app, which is included by default with the OS X install), or through various GUIs. Although it might be initially intimidating, we encourage using the Terminal app to set the basic configuration of Git.

To operate properly, Git needs to be able to identify its user. You can set these by entering a few basic commands in the Terminal. To verify the current user information, type `git config --global user.name`, and hit return. This should not return anything, unless a previous user of the computer has set it. To ensure that Git knows who you are, type `git config --global user.name "User Name"` (where User Name is your name), and hit return. If you now re-run the first command, Terminal will return the name you entered as `"User Name"`. The second piece of information is your email, which can be entered by `git config --global user.email "email@address.com"` (where email@address.com is your email address). You can verify that the correct email address was saved by typing `git config --global user.email` in the Terminal, and hit return. Once this information is entered, Git will know who you are, and is thus able to track who is doing what within a project, which is especially helpful when you are collaborating with other people.

### Windows

Windows users can download the Git software installer from <http://git-scm.com/download/win>. [TODO]

# Using Git

The first operating principle of Git is that work is organized into independent projects, which Git calls *repositories*. At its core, a repository is a folder on your computer, which is version controlled by Git. Everything that happens inside that folder is tracked by Git, but the user has full control of what is tracked (everything, by default) and when. To establish the operating principles of Git, we now turn to a practical example using a hypothetical project that, we feel, reflects the components of a typical project in experimental psychology.

## Organizing files and folders

Observers have noted that implementing reproducibility into the scientific workflow is less time-consuming if it is planned from the onset of the project, rather than attempting to add reproducibility to the project after it has been completed [TODO]. To that end, it is important to organize the project keeping a few key goals in mind (here, we broadly follow established guidelines such as Project TIER recommendations): The files and folders should have easy to understand names (avoid idiosynchratic naming schemes), and the names should indicate the purposes of the files and folders. 

The example project has a home directory, which has a concise name indicating its contents. Here, we have simply called it `example-project`. Everything related to that material is placed in subfolders of the home directory: We have "conducted" one experiment in the project; this experiment had three main components: 1) the computer code that was used to present the stimuli to the participants `experiment-1/experiment/`, 2) the raw data files in `experiment-1/data/`, and 3) the code used to analyse the data in `experiment-1/analysis/`. Note that all these folders were sub-sub-directories of the home folder for the project, clearly indicating which experiment (in what may be a multi-experiment project) they refer to. 

With this initial set-up in mind, let's begin using Git to enhance the reproducibility of this project.




# Footnotes

[^git-version]: As of the writing of this article, the current version of Git is 2.13.1. 

\newpage

# References


\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
